services:
  dockge:
    image: cmcooper1980/dockge
    build:
      context: .
      dockerfile: docker/Dockerfile
    restart: unless-stopped
    ports:
      - 5001:5001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/app/data
      # - /root/.docker/:/root/.docker   # (optional) private registries
      - /opt/stacks:/opt/stacks
    environment:
      - DOCKGE_STACKS_DIR=/opt/stacks

      # Init behavior (safe defaults)
      - AUTO_CREATE_USER=1
      # - RESET_PASSWORD_ON_START=1  # uncomment only if you WANT rotation every boot

      # Supply USER either as env or as secret (choose ONE approach):
      - USER=testuser
      # USER_FILE will be read if USER is not set; uncomment if you create a user secret:
      # - USER_FILE=/run/secrets/dockge_user

      # PASSWORD will be read from PASSWORD_FILE; no need to set PASSWORD env
      - PASSWORD_FILE=/run/secrets/dockge_password

    secrets:
      - dockge_password
      # - dockge_user  # uncomment if you prefer user via secret too

    stdin_open: true # docker run -i
    tty: true        # docker run -t

secrets:
  dockge_password:
    file: ./secrets/dockge_password.txt
  # dockge_user:
  #   file: ./secrets/dockge_user.txt
